/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bootstrapSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueActionToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKeys"];
        put?: never;
        post: operations["generateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKeyAlgorithms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/hardware-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buildHardwareKeyCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{keyId}/passphrase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeKeyPassphrase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{keyId}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revealPrivateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{keyId}/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerKeyWithAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{keyId}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trashKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTrash"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/{entryId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreTrashEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trash/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["purgeTrashEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigHost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewConfigEdit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveConfigEdit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreHistoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recoverTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BootstrapResponse: {
            csrfToken: string;
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            version: string;
        };
        Problem: {
            code: string;
            message: string;
            detail?: string;
            path?: string;
            line?: number;
            column?: number;
            diagnostics?: components["schemas"]["Diagnostic"][];
            conflict?: components["schemas"]["ConflictReport"];
        };
        KeyReference: {
            directive: string;
            configPath: string;
            line: number;
            condition: string;
            hostPatterns: string[];
            value: string;
        };
        UnresolvedReference: {
            directive: string;
            value: string;
            configPath: string;
            line: number;
            reason: string;
        };
        KeyCertificate: {
            keyId: string;
            principals: string[];
            validBefore: number;
            neverExpires: boolean;
            signedKeyType: string;
            signedKeyFingerprint: string;
        };
        UnreadableFile: {
            relativePath: string;
            reason: string;
        };
        KeyItem: {
            id: string;
            relativePath: string;
            kind: string;
            container: string;
            algorithm: string;
            keyType: string;
            bits: number;
            encrypted: boolean;
            fingerprint: string;
            comment: string;
            permission: string;
            permissionRisk: boolean;
            sizeBytes: number;
            certificate?: components["schemas"]["KeyCertificate"];
            references: components["schemas"]["KeyReference"][];
            notes: string[];
        };
        AgentIdentity: {
            bits: number;
            fingerprint: string;
            comment: string;
            algorithm: string;
        };
        KeyInventoryResponse: {
            items: components["schemas"]["KeyItem"][];
            unreadable: components["schemas"]["UnreadableFile"][];
            agentDelegations: components["schemas"]["KeyReference"][];
            unresolvedReferences: components["schemas"]["UnresolvedReference"][];
            agentAvailable: boolean;
            agentIdentities: components["schemas"]["AgentIdentity"][];
        };
        KeyVariant: {
            algorithm: string;
            bits: number;
            label: string;
            inProcess: boolean;
            reason: string;
        };
        KeyAlgorithmsResponse: {
            variants: components["schemas"]["KeyVariant"][];
            source: string;
            diagnostic: string;
        };
        GenerateKeyRequest: {
            algorithm: string;
            bits?: number;
            fileName: string;
            comment: string;
            passphrase: string;
            unencrypted: boolean;
        };
        GenerateKeyResponse: {
            id: string;
            relativePath: string;
            publicRelativePath: string;
            fingerprint: string;
            keyType: string;
            bits: number;
            encrypted: boolean;
            transactionId: string;
        };
        HardwareCommandRequest: {
            algorithm: string;
            fileName: string;
            comment: string;
        };
        HardwareCommandResponse: {
            algorithm: string;
            command: string[];
            note: string;
        };
        ChangePassphraseRequest: {
            currentPassphrase: string;
            newPassphrase: string;
            unencrypted: boolean;
        };
        ChangePassphraseResponse: {
            id: string;
            relativePath: string;
            encrypted: boolean;
            notes: string[];
            transactionId: string;
        };
        RevealPrivateKeyResponse: {
            id: string;
            relativePath: string;
            privateKey: string;
            encrypted: boolean;
            fingerprint: string;
            transactionId: string;
        };
        IssueActionRequest: {
            kind: string;
            target: string;
        };
        IssueActionResponse: {
            token: string;
            expiresAt: string;
        };
        RegisterKeyRequest: {
            passphrase: string;
            lifetimeSeconds: number;
            storeInKeychain: boolean;
        };
        RegisterKeyResponse: {
            id: string;
            relativePath: string;
            fingerprint: string;
            lifetimeSeconds: number;
            storedInKeychain: boolean;
            identities: components["schemas"]["AgentIdentity"][];
        };
        TrashFileSummary: {
            originalRelativePath: string;
            trashRelativePath: string;
            kind: string;
            fingerprint: string;
            permission: string;
        };
        TrashEntrySummary: {
            id: string;
            deletedAt: string;
            ageDays: number;
            stale: boolean;
            files: components["schemas"]["TrashFileSummary"][];
            restorable: boolean;
            blockers: string[];
        };
        TrashListResponse: {
            entries: components["schemas"]["TrashEntrySummary"][];
            retentionDays: number;
        };
        TrashKeyResponse: {
            entryId: string;
            files: components["schemas"]["TrashFileSummary"][];
            skipped: string[];
            transactionId: string;
        };
        RestoreTrashResponse: {
            entryId: string;
            restored: string[];
            blockers: string[];
            transactionId: string;
        };
        PurgeTrashResponse: {
            entryId: string;
            removed: string[];
            transactionId: string;
        };
        FileRef: {
            path?: string;
            absolute: string;
            external?: boolean;
        };
        Notice: {
            code: string;
            path?: string;
            line?: number;
            detail?: string;
        };
        Diagnostic: {
            severity: string;
            code: string;
            path?: string;
            absolute?: string;
            external?: boolean;
            line?: number;
            detail?: string;
        };
        HostIdentity: {
            path: string;
            alias: string;
        };
        HostEntry: {
            identity: components["schemas"]["HostIdentity"];
            file: components["schemas"]["FileRef"];
            line: number;
            patterns: string[];
            wildcard?: boolean;
            negated?: boolean;
            duplicate?: boolean;
            editable: boolean;
        };
        IncludeReference: {
            line: number;
            pattern: string;
            condition?: string;
            matches?: components["schemas"]["FileRef"][];
        };
        FileNode: {
            file: components["schemas"]["FileRef"];
            missing?: boolean;
            editable: boolean;
            loads: number;
            includes?: components["schemas"]["IncludeReference"][];
        };
        Setting: {
            keyword: string;
            values: string[];
        };
        HostMetadata: {
            identity: components["schemas"]["HostIdentity"];
            group?: string;
            tags?: string[];
            colour?: string;
            note?: string;
            favourite?: boolean;
            order?: number;
            orphan?: boolean;
        };
        GroupMetadata: {
            name: string;
            parent?: string;
            colour?: string;
            note?: string;
            order?: number;
            settings?: components["schemas"]["Setting"][];
        };
        Metadata: {
            schemaVersion: number;
            groupsFile?: string;
            groups?: components["schemas"]["GroupMetadata"][];
            hosts?: components["schemas"]["HostMetadata"][];
        };
        PendingTransaction: {
            id: string;
            operation: string;
            status: string;
            startedAt: string;
            committed: number;
            paths: string[];
            canComplete: boolean;
        };
        Overview: {
            entry: components["schemas"]["FileRef"];
            files: components["schemas"]["FileNode"][];
            hosts: components["schemas"]["HostEntry"][];
            metadata: components["schemas"]["Metadata"];
            diagnostics: components["schemas"]["Diagnostic"][];
            notices: components["schemas"]["Notice"][];
            pending?: components["schemas"]["PendingTransaction"][];
        };
        FormField: {
            line: number;
            keyword: string;
            values: string[];
            category: string;
            dangerous?: boolean;
            duplicate?: boolean;
            editable: boolean;
        };
        HostForm: {
            entry: components["schemas"]["HostEntry"];
            fields: components["schemas"]["FormField"][];
            raw: string;
            notices?: components["schemas"]["Notice"][];
        };
        Source: {
            path?: string;
            absolute?: string;
            line?: number;
            condition?: string;
        };
        EffectiveEntry: {
            keyword: string;
            values: string[];
            source: components["schemas"]["Source"];
        };
        Effective: {
            alias: string;
            approximate: boolean;
            entries: components["schemas"]["EffectiveEntry"][];
            notices?: components["schemas"]["Notice"][];
        };
        FileContents: {
            file: components["schemas"]["FileRef"];
            contents: string;
            digest: string;
            editable: boolean;
            exists: boolean;
        };
        HostDetail: {
            form: components["schemas"]["HostForm"];
            metadata: components["schemas"]["HostMetadata"];
            effective: components["schemas"]["Effective"];
            file: components["schemas"]["FileContents"];
        };
        FieldEdit: {
            action: string;
            line?: number;
            keyword?: string;
            values?: string[];
        };
        EditRequest: {
            kind: string;
            path?: string;
            base?: string;
            alias?: string;
            newAlias?: string;
            fields?: components["schemas"]["FieldEdit"][];
            raw?: string;
            metadata?: components["schemas"]["Metadata"];
        };
        DiffLine: {
            op: string;
            text: string;
            oldLine?: number;
            newLine?: number;
        };
        FileDiff: {
            path: string;
            created?: boolean;
            removed?: boolean;
            oldDigest?: string;
            newDigest?: string;
            lines: components["schemas"]["DiffLine"][];
            truncated?: boolean;
        };
        EffectiveChange: {
            keyword: string;
            before: string[];
            after: string[];
            beforeSources?: components["schemas"]["Source"][];
            afterSources?: components["schemas"]["Source"][];
        };
        EffectiveDiff: {
            alias: string;
            changes: components["schemas"]["EffectiveChange"][];
        };
        SavePreview: {
            operation: string;
            diffs: components["schemas"]["FileDiff"][];
            effective?: components["schemas"]["EffectiveDiff"][];
            notices?: components["schemas"]["Notice"][];
        };
        SaveResult: {
            transactionId: string;
            written: string[];
            preview: components["schemas"]["SavePreview"];
        };
        ConflictReport: {
            path: string;
            baseDigest?: string;
            diskDigest?: string;
            externalChange: components["schemas"]["DiffLine"][];
            localChange: components["schemas"]["DiffLine"][];
        };
        HistoryEntry: {
            id: string;
            operation: string;
            status: string;
            startedAt: string;
            finishedAt?: string;
            paths: string[];
            restorable?: string[];
        };
        HistoryList: {
            entries: components["schemas"]["HistoryEntry"][];
        };
        RestoreRequest: {
            transactionId: string;
            path: string;
        };
        RecoverRequest: {
            transactionId: string;
            action: string;
        };
        RecoverResponse: {
            /** @constant */
            status: "ok";
        };
    };
    responses: {
        /** @description Request rejected */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bootstrapSession: {
        parameters: {
            query?: never;
            header: {
                "X-SSH-UI-Bootstrap": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session established */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated process health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    issueActionToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueActionRequest"];
            };
        };
        responses: {
            /** @description One-time action token issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueActionResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Classified contents of the ssh workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyInventoryResponse"];
                };
            };
            401: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    generateKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateKeyRequest"];
            };
        };
        responses: {
            /** @description Key pair generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateKeyResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listKeyAlgorithms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Variants the installed OpenSSH supports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyAlgorithmsResponse"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    buildHardwareKeyCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HardwareCommandRequest"];
            };
        };
        responses: {
            /** @description Command the user runs in Terminal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareCommandResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    changeKeyPassphrase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassphraseRequest"];
            };
        };
        responses: {
            /** @description Passphrase changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePassphraseResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    revealPrivateKey: {
        parameters: {
            query?: never;
            header: {
                "X-SSH-UI-Action": string;
            };
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private key material, never cached and never logged */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealPrivateKeyResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    registerKeyWithAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterKeyRequest"];
            };
        };
        responses: {
            /** @description Key registered with the ssh-agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterKeyResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
        };
    };
    trashKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key moved to the trash */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashKeyResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listTrash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted keys, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrashListResponse"];
                };
            };
            401: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    restoreTrashEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trash entry restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreTrashResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            /** @description Restore refused because it would have to guess */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreTrashResponse"];
                };
            };
        };
    };
    purgeTrashEntry: {
        parameters: {
            query?: never;
            header: {
                "X-SSH-UI-Action": string;
            };
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trash entry permanently deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeTrashResponse"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getConfigOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Include tree, hosts, groups and diagnostics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            401: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    getConfigHost: {
        parameters: {
            query: {
                path: string;
                alias: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One host block with its explained values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getConfigFile: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One configuration file for the raw editor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContents"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    previewConfigEdit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Exactly what a save would write */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavePreview"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    saveConfigEdit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Committed transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UI-only organisation data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metadata"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed transactions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryList"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    restoreHistoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRequest"];
            };
        };
        responses: {
            /** @description Restored file committed as a new transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    recoverTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoverRequest"];
            };
        };
        responses: {
            /** @description Interrupted transaction completed or rolled back */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoverResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
}
