// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// Problem defines model for Problem.
type Problem struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// BootstrapSessionParams defines parameters for BootstrapSession.
type BootstrapSessionParams struct {
	XSSHUIBootstrap string `json:"X-SSH-UI-Bootstrap"`
}
