package application

import (
	"os"
	"path/filepath"
	"testing"

	"ssh-ui/internal/config"
)

// groupFixture is the same hierarchy the parent-field version described, said
// the way the filesystem says it: "work" is nested inside "company" because its
// directory is, and each host is in the group its file sits in.
func groupFixture() ([]string, Metadata, []HostEntry) {
	metadata := NewMetadata()
	metadata.Groups = []GroupMetadata{
		{Name: "company", Settings: []Setting{{Keyword: "ServerAliveInterval", Values: []string{"30"}}}},
		{Name: "company/work", Settings: []Setting{
			{Keyword: "User", Values: []string{"ops"}},
			{Keyword: "Port", Values: []string{"2222"}},
		}},
	}
	hosts := []HostEntry{
		{Identity: HostIdentity{Path: "connections/company/work/build.conf", Alias: "build01"}, Group: "company/work"},
		{Identity: HostIdentity{Path: "connections/company/web.conf", Alias: "web01"}, Group: "company"},
	}
	return []string{"company/work", "company"}, metadata, hosts
}

func TestCompileGroupsPutsChildrenBeforeParentsAndInheritsMembers(t *testing.T) {
	declared, metadata, hosts := groupFixture()

	contents, notices := CompileGroups(declared, metadata, hosts, "\n")
	const want = `# Generated by ssh-ui from ~/.ssh/ssh-ui/metadata.json.
# Child groups come first because OpenSSH keeps the first value it reads.
# Edit groups in the UI; hand edits to this file are replaced on the next save.

# group company/work (parent company)
Host build01
	User ops
	Port 2222

# group company
Host build01 web01
	ServerAliveInterval 30
`
	if got := string(contents); got != want {
		t.Fatalf("contents =\n%q\nwant\n%q", got, want)
	}
	// A member that is not in the projection is not a notice any more: there is
	// no second list of members to disagree with the files on disk.
	if len(notices) != 0 {
		t.Fatalf("notices = %#v", notices)
	}
}

func TestCompileGroupsRendersParsableLosslessConfiguration(t *testing.T) {
	declared, metadata, hosts := groupFixture()
	contents, _ := CompileGroups(declared, metadata, hosts, "\n")
	parsed := config.Parse(contents)
	if string(parsed.Render()) != string(contents) {
		t.Fatal("generated group configuration does not round-trip")
	}
	for index, line := range parsed.Lines {
		if line.Kind == config.LineUnstructured {
			t.Fatalf("generated line %d is unstructured: %q", index+1, line.Text)
		}
	}
}

// A group name is a directory path, so a hierarchy cannot contain a cycle: the
// test that proved cycles were excluded is replaced by the one that proves they
// are unrepresentable.
func TestAGroupCanNeverBeItsOwnAncestor(t *testing.T) {
	for _, name := range []string{"a/b/c", "work", "a/b/a"} {
		seen := map[string]bool{}
		for current := name; current != ""; current = ParentGroupName(current) {
			if seen[current] {
				t.Fatalf("%q reaches %q twice", name, current)
			}
			seen[current] = true
		}
	}
}

func regionFile(t *testing.T, groups ...string) *config.File {
	t.Helper()
	file := config.Parse(nil)
	plan, err := PlanRegion(file, groups, DefaultGroupsFile)
	if err != nil {
		t.Fatalf("PlanRegion error = %v", err)
	}
	if err := ApplyRegion(file, plan); err != nil {
		t.Fatalf("ApplyRegion error = %v", err)
	}
	return file
}

func TestDeclaredGroupsReadsTheRegionAndNothingElse(t *testing.T) {
	file := regionFile(t, "work/eu", "work", "home")
	declared := DeclaredGroups(file)
	want := []string{"work/eu", "work", "home"}
	if len(declared) != len(want) {
		t.Fatalf("declared = %#v", declared)
	}
	for index := range want {
		if declared[index] != want[index] {
			t.Fatalf("declared = %#v, want %#v", declared, want)
		}
	}

	// An Include the user wrote themselves, outside the markers, declares
	// nothing: the region is the declaration, not every line that happens to
	// name a directory.
	handWritten := config.Parse([]byte("Include connections/marketing/*.conf\n"))
	if got := DeclaredGroups(handWritten); len(got) != 0 {
		t.Errorf("DeclaredGroups outside the region = %#v, want none", got)
	}
}

func TestBuildGroupsViewReportsADirectoryThatWasNeverDeclared(t *testing.T) {
	// ~/.ssh/connections/marketing exists and no line names it. Adopting it
	// would mean this application deciding that somebody else's directory is
	// one of its groups.
	views, notices := BuildGroupsView(regionFile(t, "work"), nil, NewMetadata(), []string{"work", "marketing"})

	if len(views) != 1 || views[0].Name != "work" {
		t.Fatalf("views = %#v, want only the declared group", views)
	}
	if !hasNotice(notices, NoticeGroupNotDeclared, "marketing") {
		t.Errorf("notices = %#v, want group_not_declared for marketing", notices)
	}
}

func TestBuildGroupsViewReportsADeclaredGroupWithNoDirectory(t *testing.T) {
	views, notices := BuildGroupsView(regionFile(t, "work"), nil, NewMetadata(), nil)

	if len(views) != 1 || views[0].DirectoryPresent {
		t.Fatalf("views = %#v", views)
	}
	if !hasNotice(notices, NoticeGroupDirectoryMissing, "work") {
		t.Errorf("notices = %#v, want group_directory_missing", notices)
	}
}

func TestBuildGroupsViewReportsADeclaredGroupWithNoMembers(t *testing.T) {
	views, notices := BuildGroupsView(regionFile(t, "work"), nil, NewMetadata(), []string{"work"})

	if len(views) != 1 || views[0].MemberCount != 0 {
		t.Fatalf("views = %#v", views)
	}
	if !hasNotice(notices, NoticeGroupEmpty, "work") {
		t.Errorf("notices = %#v, want group_empty", notices)
	}
}

func TestBuildGroupsViewCarriesTheDirectoriesAndTheHierarchy(t *testing.T) {
	metadata := NewMetadata()
	metadata.Groups = []GroupMetadata{{Name: "work/eu", Colour: "#f97316"}}
	hosts := []HostEntry{
		{Identity: HostIdentity{Path: "connections/work/eu/lon.conf", Alias: "lon-1"}, Group: "work/eu"},
	}
	views, _ := BuildGroupsView(regionFile(t, "work/eu", "work"), hosts, metadata, []string{"work", "work/eu"})

	if len(views) != 2 || views[0].Name != "work/eu" {
		t.Fatalf("views = %#v, want the child first", views)
	}
	child := views[0]
	if child.Parent != "work" || child.Directory != "connections/work/eu" || child.KeyDirectory != "keys/work/eu" {
		t.Errorf("child = %#v", child)
	}
	if child.MemberCount != 1 || child.Colour != "#f97316" {
		t.Errorf("child = %#v", child)
	}
}

func hasNotice(notices []Notice, code, detail string) bool {
	for _, notice := range notices {
		if notice.Code == code && notice.Detail == detail {
			return true
		}
	}
	return false
}

// The three group diagnostics reach the screen that shows groups.
//
// They were computed, tested, and served by nothing: a directory under
// connections/ that no Include names, a declared group whose directory is gone,
// and a declared group with nothing in it were all invisible. Each is a state
// somebody has to act on, and the first is the one that silently does nothing.
func TestTheOverviewCarriesTheGroupDiagnostics(t *testing.T) {
	service, workspace := newTestService(t)
	declareGroup(t, service, "work", "archive")
	writeGroupFile(t, workspace, "work", "web.conf", "Host web-1\n\tHostName 203.0.113.10\n")
	// archive is declared and its directory holds nothing.
	// scratch is a directory nothing declares.
	if err := os.MkdirAll(filepath.Join(workspace.Root(), "connections", "scratch"), 0o700); err != nil {
		t.Fatal(err)
	}
	// gone is declared and its directory is not there.
	declareGroup(t, service, "work", "archive", "gone")
	if err := os.RemoveAll(filepath.Join(workspace.Root(), "connections", "gone")); err != nil {
		t.Fatal(err)
	}

	overview, err := service.Overview()
	if err != nil {
		t.Fatalf("Overview = %v", err)
	}
	for _, want := range []struct{ code, detail string }{
		{NoticeGroupNotDeclared, "scratch"},
		{NoticeGroupEmpty, "archive"},
		{NoticeGroupDirectoryMissing, "gone"},
	} {
		if !hasNotice(overview.Notices, want.code, want.detail) {
			t.Errorf("notices = %#v, want %s for %s", overview.Notices, want.code, want.detail)
		}
	}
	// And the groups themselves travel, with what each holds.
	byName := map[string]GroupView{}
	for _, group := range overview.Groups {
		byName[group.Name] = group
	}
	if got := byName["work"]; got.MemberCount != 1 || !got.DirectoryPresent {
		t.Errorf("work = %#v, want one member and a directory", got)
	}
	if got := byName["gone"]; got.DirectoryPresent {
		t.Errorf("gone reports a directory it does not have: %#v", got)
	}
}
