package application

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"sshc/internal/config"
)

// groupFixture は、parent フィールド版が記述していたのと同じ階層を、
// ファイルシステムの言い方で述べる: "work" が "company" の中にネストしているのは
// そのディレクトリがそうだからであり、各 host はそのファイルが置かれたグループに属す。
func groupFixture() ([]string, Metadata, []HostEntry) {
	metadata := NewMetadata()
	metadata.Groups = []GroupMetadata{
		{Name: "company", Settings: []Setting{{Keyword: "ServerAliveInterval", Values: []string{"30"}}}},
		{Name: "company/work", Settings: []Setting{
			{Keyword: "User", Values: []string{"ops"}},
			{Keyword: "Port", Values: []string{"2222"}},
		}},
	}
	hosts := []HostEntry{
		{Identity: HostIdentity{Path: "connections/company/work/build.conf", Alias: "build01"}, Group: "company/work"},
		{Identity: HostIdentity{Path: "connections/company/web.conf", Alias: "web01"}, Group: "company"},
	}
	return []string{"company/work", "company"}, metadata, hosts
}

func TestCompileGroupsPutsChildrenBeforeParentsAndInheritsMembers(t *testing.T) {
	declared, metadata, hosts := groupFixture()

	contents, notices := CompileGroups(declared, metadata, hosts, "\n")
	const want = `# Generated by sshc from ~/.ssh/sshc/metadata.json.
# Child groups come first because OpenSSH keeps the first value it reads.
# Edit groups in the UI; hand edits to this file are replaced on the next save.

# group company/work (parent company)
Host build01
	User ops
	Port 2222

# group company
Host build01 web01
	ServerAliveInterval 30
`
	if got := string(contents); got != want {
		t.Fatalf("contents =\n%q\nwant\n%q", got, want)
	}
	// 射影に無いメンバーはもはや notice ではない: ディスク上の
	// ファイルと食い違いうる 2 つ目のメンバー一覧は存在しないからだ。
	if len(notices) != 0 {
		t.Fatalf("notices = %#v", notices)
	}
}

func TestCompileGroupsRendersParsableLosslessConfiguration(t *testing.T) {
	declared, metadata, hosts := groupFixture()
	contents, _ := CompileGroups(declared, metadata, hosts, "\n")
	parsed := config.Parse(contents)
	if string(parsed.Render()) != string(contents) {
		t.Fatal("generated group configuration does not round-trip")
	}
	for index, line := range parsed.Lines {
		if line.Kind == config.LineUnstructured {
			t.Fatalf("generated line %d is unstructured: %q", index+1, line.Text)
		}
	}
}

// グループ名はディレクトリパスなので、階層は循環を含み得ない:
// 循環が排除されていることを証明していたテストは、循環が
// そもそも表現不能であることを証明するテストに置き換えられた。
func TestAGroupCanNeverBeItsOwnAncestor(t *testing.T) {
	for _, name := range []string{"a/b/c", "work", "a/b/a"} {
		seen := map[string]bool{}
		for current := name; current != ""; current = ParentGroupName(current) {
			if seen[current] {
				t.Fatalf("%q reaches %q twice", name, current)
			}
			seen[current] = true
		}
	}
}

func regionFile(t *testing.T, groups ...string) *config.File {
	t.Helper()
	file := config.Parse(nil)
	plan, err := PlanRegion(file, groups, DefaultGroupsFile)
	if err != nil {
		t.Fatalf("PlanRegion error = %v", err)
	}
	if err := ApplyRegion(file, plan); err != nil {
		t.Fatalf("ApplyRegion error = %v", err)
	}
	return file
}

func TestDeclaredGroupsReadsTheRegionAndNothingElse(t *testing.T) {
	file := regionFile(t, "work/eu", "work", "home")
	declared := DeclaredGroups(file)
	want := []string{"work/eu", "work", "home"}
	if len(declared) != len(want) {
		t.Fatalf("declared = %#v", declared)
	}
	for index := range want {
		if declared[index] != want[index] {
			t.Fatalf("declared = %#v, want %#v", declared, want)
		}
	}

	// マーカーの外にユーザー自身が書いた Include は何も宣言しない:
	// 宣言なのは region であって、たまたまディレクトリを名指しする
	// すべての行ではない。
	handWritten := config.Parse([]byte("Include connections/marketing/*.conf\n"))
	if got := DeclaredGroups(handWritten); len(got) != 0 {
		t.Errorf("DeclaredGroups outside the region = %#v, want none", got)
	}
}

func TestBuildGroupsViewReportsADirectoryThatWasNeverDeclared(t *testing.T) {
	// ~/.ssh/connections/marketing は存在するが、どの行もそれを
	// 名指ししない。それを採用するとしたら、このアプリケーションが
	// 他人のディレクトリを自分のグループの 1 つだと決めつけることになる。
	views, notices := BuildGroupsView(regionFile(t, "work"), nil, NewMetadata(), []string{"work", "marketing"})

	if len(views) != 1 || views[0].Name != "work" {
		t.Fatalf("views = %#v, want only the declared group", views)
	}
	if !hasNotice(notices, NoticeGroupNotDeclared, "marketing") {
		t.Errorf("notices = %#v, want group_not_declared for marketing", notices)
	}
}

func TestBuildGroupsViewReportsADeclaredGroupWithNoDirectory(t *testing.T) {
	views, notices := BuildGroupsView(regionFile(t, "work"), nil, NewMetadata(), nil)

	if len(views) != 1 || views[0].DirectoryPresent {
		t.Fatalf("views = %#v", views)
	}
	if !hasNotice(notices, NoticeGroupDirectoryMissing, "work") {
		t.Errorf("notices = %#v, want group_directory_missing", notices)
	}
}

func TestBuildGroupsViewReportsADeclaredGroupWithNoMembers(t *testing.T) {
	views, notices := BuildGroupsView(regionFile(t, "work"), nil, NewMetadata(), []string{"work"})

	if len(views) != 1 || views[0].MemberCount != 0 {
		t.Fatalf("views = %#v", views)
	}
	if !hasNotice(notices, NoticeGroupEmpty, "work") {
		t.Errorf("notices = %#v, want group_empty", notices)
	}
}

func TestBuildGroupsViewCarriesTheDirectoriesAndTheHierarchy(t *testing.T) {
	metadata := NewMetadata()
	metadata.Groups = []GroupMetadata{{Name: "work/eu", Colour: "#f97316"}}
	hosts := []HostEntry{
		{Identity: HostIdentity{Path: "connections/work/eu/lon.conf", Alias: "lon-1"}, Group: "work/eu"},
	}
	views, _ := BuildGroupsView(regionFile(t, "work/eu", "work"), hosts, metadata, []string{"work", "work/eu"})

	if len(views) != 2 || views[0].Name != "work/eu" {
		t.Fatalf("views = %#v, want the child first", views)
	}
	child := views[0]
	if child.Parent != "work" || child.Directory != "connections/work/eu" || child.KeyDirectory != "keys/work/eu" {
		t.Errorf("child = %#v", child)
	}
	if child.MemberCount != 1 || child.Colour != "#f97316" {
		t.Errorf("child = %#v", child)
	}
}

func hasNotice(notices []Notice, code, detail string) bool {
	for _, notice := range notices {
		if notice.Code == code && notice.Detail == detail {
			return true
		}
	}
	return false
}

// 3 つのグループ診断は、グループを表示する画面に届く。
//
// それらは計算され、テストされていたが、何にも提供されていなかった: どの
// Include も名指ししない connections/ 配下のディレクトリ、ディレクトリが消えた
// 宣言済みグループ、中身のない宣言済みグループは、すべて見えなかった。それぞれは
// 誰かが対処すべき状態であり、最初のものは黙って何もしないという状態である。
func TestTheOverviewCarriesTheGroupDiagnostics(t *testing.T) {
	service, workspace := newTestService(t)
	declareGroup(t, service, "work", "archive")
	writeGroupFile(t, workspace, "work", "web.conf", "Host web-1\n\tHostName 203.0.113.10\n")
	// archive は宣言されており、そのディレクトリは何も保持していない。
	// scratch は何にも宣言されていないディレクトリである。
	if err := os.MkdirAll(filepath.Join(workspace.Root(), "connections", "scratch"), 0o700); err != nil {
		t.Fatal(err)
	}
	// gone は宣言されているが、そのディレクトリは存在しない。
	declareGroup(t, service, "work", "archive", "gone")
	if err := os.RemoveAll(filepath.Join(workspace.Root(), "connections", "gone")); err != nil {
		t.Fatal(err)
	}

	overview, err := service.Overview()
	if err != nil {
		t.Fatalf("Overview = %v", err)
	}
	for _, want := range []struct{ code, detail string }{
		{NoticeGroupNotDeclared, "scratch"},
		{NoticeGroupEmpty, "archive"},
		{NoticeGroupDirectoryMissing, "gone"},
	} {
		if !hasNotice(overview.Notices, want.code, want.detail) {
			t.Errorf("notices = %#v, want %s for %s", overview.Notices, want.code, want.detail)
		}
	}
	// そしてグループ自体も、それぞれが保持するものと共に運ばれる。
	byName := map[string]GroupView{}
	for _, group := range overview.Groups {
		byName[group.Name] = group
	}
	if got := byName["work"]; got.MemberCount != 1 || !got.DirectoryPresent {
		t.Errorf("work = %#v, want one member and a directory", got)
	}
	if got := byName["gone"]; got.DirectoryPresent {
		t.Errorf("gone reports a directory it does not have: %#v", got)
	}
}

// マーカーが 1 つしかない region は壊れた region であり、
// 4 つのディレクトリが「宣言されていない」と言うのは実際に起きたこととは違う。
//
// Include 行は存在し、OpenSSH はそれを読む。欠けているのは
// 終端マーカーであり、このアプリケーションは自分が生成した行が
// どこで終わるか分からなくなる — そのためすべてのグループが未宣言に
// 見えてしまった。4 つの誤解を招く notice が、1 つの真実の notice に置き換えられた。
func TestADamagedRegionIsReportedAsItselfRatherThanAsUndeclaredGroups(t *testing.T) {
	service, workspace := newTestService(t)
	declareGroup(t, service, "work")
	writeGroupFile(t, workspace, "work", "web.conf", "Host web-1\n")

	// 終端マーカーを取り除く。それは手動編集が残す状態である。
	entry := readFile(t, workspace, "config")
	damaged := strings.ReplaceAll(entry, RegionEndMarker+"\n", "")
	if damaged == entry {
		t.Fatalf("the fixture has no end marker to remove: %q", entry)
	}
	if err := os.WriteFile(filepath.Join(workspace.Root(), "config"), []byte(damaged), 0o600); err != nil {
		t.Fatal(err)
	}

	overview, err := service.Overview()
	if err != nil {
		t.Fatalf("Overview = %v", err)
	}
	if !hasNotice(overview.Notices, NoticeRegionDamaged, "") {
		t.Errorf("notices = %#v, want %s", overview.Notices, NoticeRegionDamaged)
	}
	for _, notice := range overview.Notices {
		if notice.Code == NoticeGroupNotDeclared {
			t.Errorf("a damaged region was reported as an undeclared group: %#v", notice)
		}
	}
}
