package application

import (
	"sort"
	"strings"

	"ssh-ui/internal/config"
)

// maxGroupDepth bounds the parent walk so a malformed hierarchy cannot loop.
const maxGroupDepth = 32

// GroupDepthOrder sorts groups deepest first, which is the order OpenSSH needs:
// a child's Host block must be read before its parent's so the child's value is
// the first value found. Groups in a parent cycle are excluded and reported.
func GroupDepthOrder(groups []GroupMetadata) ([]GroupMetadata, []Notice) {
	byName := make(map[string]GroupMetadata, len(groups))
	for _, group := range groups {
		byName[group.Name] = group
	}
	depths := make(map[string]int, len(groups))
	ordered := make([]GroupMetadata, 0, len(groups))
	var notices []Notice
	for _, group := range groups {
		depth, ok := groupDepth(byName, group.Name, map[string]bool{})
		if !ok {
			notices = appendNotice(notices, Notice{Code: NoticeGroupCycle, Detail: group.Name})
			continue
		}
		depths[group.Name] = depth
		ordered = append(ordered, group)
	}
	sort.SliceStable(ordered, func(first, second int) bool {
		firstDepth, secondDepth := depths[ordered[first].Name], depths[ordered[second].Name]
		if firstDepth != secondDepth {
			return firstDepth > secondDepth
		}
		if ordered[first].Order != ordered[second].Order {
			return ordered[first].Order < ordered[second].Order
		}
		return ordered[first].Name < ordered[second].Name
	})
	return ordered, notices
}

func groupDepth(byName map[string]GroupMetadata, name string, seen map[string]bool) (int, bool) {
	if seen[name] || len(seen) > maxGroupDepth {
		return 0, false
	}
	group, ok := byName[name]
	if !ok || group.Parent == "" {
		return 0, true
	}
	seen[name] = true
	parentDepth, ok := groupDepth(byName, group.Parent, seen)
	if !ok {
		return 0, false
	}
	return parentDepth + 1, true
}

func isDescendantGroup(byName map[string]GroupMetadata, candidate, ancestor string) bool {
	current := candidate
	for depth := 0; depth < maxGroupDepth; depth++ {
		group, ok := byName[current]
		if !ok || group.Parent == "" {
			return false
		}
		if group.Parent == ancestor {
			return true
		}
		current = group.Parent
	}
	return false
}

// CompileGroups renders the group hierarchy as ordinary Host blocks. A parent
// block lists its own members and every member of its descendants, so a child
// inherits by being named in both blocks while its own block is read first.
func CompileGroups(metadata Metadata, hosts []HostEntry, ending string) ([]byte, []Notice) {
	if ending == "" {
		ending = "\n"
	}
	ordered, notices := GroupDepthOrder(metadata.Groups)
	byName := make(map[string]GroupMetadata, len(metadata.Groups))
	for _, group := range metadata.Groups {
		byName[group.Name] = group
	}

	aliasOrder := make([]string, 0, len(hosts))
	known := make(map[string]bool, len(hosts))
	for _, host := range hosts {
		if host.Identity.IsZero() || known[host.Identity.Alias] {
			continue
		}
		known[host.Identity.Alias] = true
		aliasOrder = append(aliasOrder, host.Identity.Alias)
	}

	direct := make(map[string][]string, len(ordered))
	for _, host := range metadata.Hosts {
		if host.Group == "" {
			continue
		}
		if !known[host.Identity.Alias] {
			notices = appendNotice(notices, Notice{
				Code: NoticeGroupMemberMissing, Path: host.Identity.Path, Detail: host.Identity.Alias,
			})
			continue
		}
		direct[host.Group] = append(direct[host.Group], host.Identity.Alias)
	}

	var builder strings.Builder
	for _, comment := range []string{
		"# Generated by ssh-ui from ~/.ssh/ssh-ui/metadata.json.",
		"# Child groups come first because OpenSSH keeps the first value it reads.",
		"# Edit groups in the UI; hand edits to this file are replaced on the next save.",
	} {
		builder.WriteString(comment)
		builder.WriteString(ending)
	}

	for _, group := range ordered {
		members := groupMembers(byName, direct, aliasOrder, group.Name)
		if len(members) == 0 || len(group.Settings) == 0 {
			continue
		}
		header, err := buildLine("", "Host", members, ending)
		if err != nil {
			notices = appendNotice(notices, Notice{Code: NoticeGroupMemberMissing, Detail: group.Name})
			continue
		}
		var block strings.Builder
		valid := true
		for _, setting := range group.Settings {
			line, settingErr := buildDirectiveLine("\t", setting.Keyword, setting.Values, ending)
			if settingErr != nil {
				notices = appendNotice(notices, Notice{
					Code: NoticeComplexExternalRule, Detail: group.Name + ": " + setting.Keyword,
				})
				valid = false
				break
			}
			block.WriteString(line.Render())
		}
		if !valid {
			continue
		}

		builder.WriteString(ending)
		builder.WriteString("# group " + group.Name)
		if group.Parent != "" {
			builder.WriteString(" (parent " + group.Parent + ")")
		}
		builder.WriteString(ending)
		builder.WriteString(header.Render())
		builder.WriteString(block.String())
	}
	return []byte(builder.String()), notices
}

func groupMembers(byName map[string]GroupMetadata, direct map[string][]string, aliasOrder []string, name string) []string {
	collected := make(map[string]bool)
	for candidate := range byName {
		if candidate != name && !isDescendantGroup(byName, candidate, name) {
			continue
		}
		for _, alias := range direct[candidate] {
			collected[alias] = true
		}
	}
	members := make([]string, 0, len(collected))
	for _, alias := range aliasOrder {
		if collected[alias] {
			members = append(members, alias)
		}
	}
	return members
}

// PlanGroupInclude decides where the generated groups file must be included.
//
// The Include goes after the user's own specific Host blocks and before the
// first catch-all block, so the priority is host, then child group, then parent
// group, then global default. An Include naming the file exactly is treated as
// already present; a glob that happens to match it is not, because guessing
// which glob covers which file is exactly what this application must not do.
func PlanGroupInclude(file *config.File, relative string) (int, bool) {
	insertAt := len(file.Lines)
	found := false
	for index, line := range file.Lines {
		if line.Kind != config.LineDirective {
			continue
		}
		if config.EqualKeyword(line.Keyword, "Include") {
			for _, value := range line.Values() {
				if value == relative {
					return -1, true
				}
			}
			continue
		}
		if found {
			continue
		}
		if config.EqualKeyword(line.Keyword, "Match") {
			insertAt, found = index, true
			continue
		}
		if !config.EqualKeyword(line.Keyword, "Host") {
			continue
		}
		for _, pattern := range line.Values() {
			if pattern == "*" {
				insertAt, found = index, true
				break
			}
		}
	}
	return insertAt, false
}

// InsertIncludeLine writes the Include directive at the planned index.
func InsertIncludeLine(file *config.File, relative string, index int) error {
	line, err := buildLine("", "Include", []string{relative}, dominantEnding(file))
	if err != nil {
		return err
	}
	if index < 0 || index > len(file.Lines) {
		return ErrEditLineOutsideBlock
	}
	insertLine(file, index, line)
	return nil
}
